//
//  StringConstants.swift
//  SolarCalculator
//
//  Created by Aakash Srivastav on 28/07/18.
//  Copyright © 2018 Aakash Srivastav. All rights reserved.
//

import Foundation

let K_APP_NAME = "K_APP_NAME"
let K_LOCATION_SERVICE_RESTRICTED = "K_LOCATION_SERVICE_RESTRICTED"
let K_LOCATION_PERMISSION_DENIED = "K_LOCATION_PERMISSION_DENIED"
let K_LOCATION_PERMISSION = "K_LOCATION_PERMISSION"
let K_SETTINGS = "K_SETTINGS"
let K_OK = "K_OK"
let K_BOOKMARKS = "K_BOOKMARKS"

let K_GOLDEN_HOUR_NOTIFICATION_TITLE = "K_GOLDEN_HOUR_NOTIFICATION_TITLE"
let K_GOLDEN_HOUR_NOTIFICATION_BODY = "K_GOLDEN_HOUR_NOTIFICATION_BODY"
